#ifndef DATATYPES_H
#define DATATYPES_H

#include <cstdint> 
#include <string>  

// Represents a single OHLCV candle/bar.
struct Bar {
    uint64_t timestamp; // Unix timestamp in milliseconds
    double open;
    double high;
    double low;
    double close;
    double volume;
};

// Defines the type of signal to be generated.
enum class SignalType {
    LONG,
    SHORT,
    EXIT,
    DO_NOTHING
};

// Represents a trading signal generated by a strategy.
struct SignalEvent {
    uint64_t timestamp;
    std::string symbol;
    SignalType type;
};

#endif // DATATYPES_H